server:
  port: 8080
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.3.3:8080/oauth2/jwks
  logging:
    level:
      org:
        springframework:
          # Pour voir les décisions d'accès (autorisé ou non)
          security: DEBUG
          # Pour voir les détails de validation du JWT
          security.oauth2: DEBUG
          # Pour voir si le WebClient de l'App A envoie bien les données
          web.servlet.DispatcherServlet: DEBUG
